sonar.projectKey=UrbanFlow-gateway

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/*.spec.ts,src/main.ts,**/*.module.ts,src/interfaces/**,src/models/**
sonar.coverage.exclusions=**/*.spec.ts,src/main.ts,**/*.module.ts,src/interfaces/**,src/models/**
